# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages

r_github_packages:
  - r-lib/covr

before_install:
  - sudo apt-get update
  - sudo apt-get install libmagic-dev

after_success:
  - Rscript -e 'covr::codecov()'
